#!/usr/bin/env python3
"""
Create AgentCore Policy Engine and Cedar Policies via boto3.

Writes policy_engine_arn and policy_engine_id to
terraform/policy-arns.auto.tfvars for Terraform to consume.

Environment variables:
  GATEWAY_ARN    - (optional) Gateway ARN for tool-specific policies
  TERRAFORM_DIR  - Path to terraform directory for writing vars file
  AWS_REGION     - AWS region (default: us-east-1)
"""

import os
import sys
import time
import boto3

REGION = os.environ.get("AWS_REGION", "us-east-1")
GATEWAY_ARN = os.environ.get("GATEWAY_ARN", "")
TERRAFORM_DIR = os.environ.get("TERRAFORM_DIR", "../terraform")
VARS_FILE = os.path.join(TERRAFORM_DIR, "policy-arns.auto.tfvars")
POLICY_ENGINE_NAME = "DataPlatformAuth"

client = boto3.client("bedrock-agentcore-control", region_name=REGION)

GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
NC = "\033[0m"


def info(msg):
    print(f"{YELLOW}→{NC} {msg}")


def ok(msg):
    print(f"{GREEN}✓{NC} {msg}")


def get_or_create_policy_engine():
    """Find existing policy engine or create a new one."""
    info("Checking for existing policy engine...")

    try:
        response = client.list_policy_engines()
        for engine in response.get("policyEngines", []):
            if engine["name"].startswith(POLICY_ENGINE_NAME):
                engine_id = engine["policyEngineId"]
                detail = client.get_policy_engine(policyEngineId=engine_id)
                ok(f"Policy engine already exists: {engine_id} (status: {detail['status']})")
                return engine_id, detail["policyEngineArn"]
    except Exception as e:
        info(f"Could not list engines: {e}")

    # Create new
    info(f"Creating policy engine: {POLICY_ENGINE_NAME}...")
    response = client.create_policy_engine(
        name=POLICY_ENGINE_NAME,
        description="Cedar authorization for the data platform gateway",
    )
    engine_id = response["policyEngineId"]
    engine_arn = response["policyEngineArn"]

    # Wait for ACTIVE
    info("Waiting for policy engine to become ACTIVE...")
    for _ in range(30):
        time.sleep(5)
        detail = client.get_policy_engine(policyEngineId=engine_id)
        if detail["status"] == "ACTIVE":
            ok(f"Policy engine ACTIVE: {engine_id}")
            return engine_id, engine_arn
        if detail["status"] not in ("CREATING",):
            print(f"ERROR: Unexpected status: {detail['status']}", file=sys.stderr)
            print(f"Reasons: {detail.get('statusReasons', [])}", file=sys.stderr)
            sys.exit(1)

    print("ERROR: Timed out waiting for policy engine", file=sys.stderr)
    sys.exit(1)


def policy_exists(engine_id, name):
    """Check if a policy with this name already exists."""
    try:
        response = client.list_policies(policyEngineId=engine_id)
        for policy in response.get("policies", []):
            if policy["name"] == name:
                return True
    except Exception:
        pass
    return False


def create_policy(engine_id, name, description, statement):
    """Create a Cedar policy if it doesn't already exist."""
    if policy_exists(engine_id, name):
        ok(f"Policy already exists: {name}")
        return

    info(f"Creating policy: {name}...")
    try:
        client.create_policy(
            policyEngineId=engine_id,
            name=name,
            description=description,
            definition={"cedar": {"statement": statement}},
            validationMode="IGNORE_ALL_FINDINGS",
        )
        ok(f"Created: {name}")
    except client.exceptions.ConflictException:
        ok(f"Policy already exists (conflict): {name}")
    except Exception as e:
        print(f"  ERROR creating {name}: {e}", file=sys.stderr)


def write_vars_file(engine_arn, engine_id):
    """Write policy ARNs to Terraform auto.tfvars file."""
    info(f"Writing {VARS_FILE}...")
    with open(VARS_FILE, "w") as f:
        f.write("# Auto-generated by scripts/create_policies.py\n")
        f.write("# Do not edit manually — re-run the script to update.\n")
        f.write(f'policy_engine_arn = "{engine_arn}"\n')
        f.write(f'policy_engine_id  = "{engine_id}"\n')
    ok(f"Wrote {VARS_FILE}")


def main():
    # Step 1: Get or create policy engine
    engine_id, engine_arn = get_or_create_policy_engine()

    # Step 2: Create admin wildcard policy (doesn't need gateway ARN)
    create_policy(
        engine_id,
        "AdminFullAccess",
        "Admins can invoke all database tools without restriction",
        'permit(principal in AgentCore::Group::"admins", action, resource is AgentCore::Gateway);',
    )

    # Step 3: Create tool-specific policies (need gateway ARN)
    if not GATEWAY_ARN:
        info("No gateway ARN available — skipping tool-specific policies.")
        info("Deploy the gateway with Terraform, then re-run this script.")
    else:
        ok(f"Gateway ARN: {GATEWAY_ARN}")

        tool_policies = [
            (
                "EngineeringRunQuery",
                "Engineers can run queries",
                f'permit(principal in AgentCore::Group::"engineering", action == AgentCore::Action::"DatabaseTools___run_query", resource == AgentCore::Gateway::"{GATEWAY_ARN}");',
            ),
            (
                "EngineeringListTables",
                "Engineers can list tables",
                f'permit(principal in AgentCore::Group::"engineering", action == AgentCore::Action::"DatabaseTools___list_tables", resource == AgentCore::Gateway::"{GATEWAY_ARN}");',
            ),
            (
                "EngineeringDescribeTable",
                "Engineers can describe tables",
                f'permit(principal in AgentCore::Group::"engineering", action == AgentCore::Action::"DatabaseTools___describe_table", resource == AgentCore::Gateway::"{GATEWAY_ARN}");',
            ),
            (
                "EngineeringForbidDelete",
                "Engineers cannot delete records",
                f'forbid(principal in AgentCore::Group::"engineering", action == AgentCore::Action::"DatabaseTools___delete_records", resource == AgentCore::Gateway::"{GATEWAY_ARN}");',
            ),
            (
                "MarketingListTables",
                "Marketing can list tables",
                f'permit(principal in AgentCore::Group::"marketing", action == AgentCore::Action::"DatabaseTools___list_tables", resource == AgentCore::Gateway::"{GATEWAY_ARN}");',
            ),
            (
                "MarketingDescribeTable",
                "Marketing can describe tables",
                f'permit(principal in AgentCore::Group::"marketing", action == AgentCore::Action::"DatabaseTools___describe_table", resource == AgentCore::Gateway::"{GATEWAY_ARN}");',
            ),
        ]

        for name, description, statement in tool_policies:
            create_policy(engine_id, name, description, statement)

        # Step 4: Attach policy engine to gateway
        attach_policy_engine_to_gateway(engine_arn)

    # Step 5: Write vars file for Terraform
    write_vars_file(engine_arn, engine_id)

    print()
    print("Done! The system is fully configured.")
    if not GATEWAY_ARN:
        print()
        print("Next steps:")
        print("  1. cd terraform && terraform apply")
        print("  2. Re-run this script to create tool-specific policies and attach the policy engine")


def attach_policy_engine_to_gateway(engine_arn):
    """Attach the policy engine to the gateway via UpdateGateway, preserving all existing config."""
    info("Attaching policy engine to gateway...")

    gateway_id = GATEWAY_ARN.split("/")[-1]

    try:
        # Get current gateway config first
        gw = client.get_gateway(gatewayIdentifier=gateway_id)

        # Check if already attached
        existing_pe = gw.get("policyEngineConfiguration", {})
        if existing_pe.get("arn") == engine_arn and existing_pe.get("mode") == "ENFORCE":
            ok("Policy engine already attached to gateway")
            return

        # Build update kwargs preserving ALL existing config
        update_kwargs = {
            "gatewayIdentifier": gateway_id,
            "name": gw["name"],
            "roleArn": gw["roleArn"],
            "protocolType": gw["protocolType"],
            "authorizerType": gw["authorizerType"],
            "authorizerConfiguration": gw.get("authorizerConfiguration", {}),
            "protocolConfiguration": gw.get("protocolConfiguration", {}),
            "policyEngineConfiguration": {
                "arn": engine_arn,
                "mode": "ENFORCE",
            },
        }

        # Preserve interceptor config if present, or set up both interceptors
        interceptor_config = gw.get("interceptorConfigurations")
        if not interceptor_config:
            # Set up both REQUEST (rate limiter) and RESPONSE (PII redactor) interceptors
            # Get the Lambda ARNs from terraform output
            import subprocess
            try:
                rate_limiter_arn = subprocess.check_output(
                    ["terraform", f"-chdir={TERRAFORM_DIR}", "output", "-raw", "rate_limiter_lambda_arn"],
                    text=True, stderr=subprocess.DEVNULL
                ).strip()
                pii_redactor_arn = subprocess.check_output(
                    ["terraform", f"-chdir={TERRAFORM_DIR}", "output", "-raw", "pii_redactor_lambda_arn"],
                    text=True, stderr=subprocess.DEVNULL
                ).strip()
            except Exception:
                rate_limiter_arn = ""
                pii_redactor_arn = ""

            if rate_limiter_arn and pii_redactor_arn:
                interceptor_config = [
                    {
                        "interceptor": {"lambda": {"arn": rate_limiter_arn}},
                        "interceptionPoints": ["REQUEST"],
                        "inputConfiguration": {"passRequestHeaders": True},
                    },
                    {
                        "interceptor": {"lambda": {"arn": pii_redactor_arn}},
                        "interceptionPoints": ["RESPONSE"],
                        "inputConfiguration": {"passRequestHeaders": True},
                    },
                ]
            elif rate_limiter_arn:
                interceptor_config = [
                    {
                        "interceptor": {"lambda": {"arn": rate_limiter_arn}},
                        "interceptionPoints": ["REQUEST"],
                        "inputConfiguration": {"passRequestHeaders": True},
                    },
                ]

        if interceptor_config:
            update_kwargs["interceptorConfigurations"] = interceptor_config

        # Preserve exception level
        if gw.get("exceptionLevel"):
            update_kwargs["exceptionLevel"] = gw["exceptionLevel"]

        client.update_gateway(**update_kwargs)
        ok("Policy engine attached to gateway (mode: ENFORCE)")
    except Exception as e:
        print(f"  WARNING: Could not attach policy engine: {e}", file=sys.stderr)
        print("  You may need to attach it manually via the AWS console.", file=sys.stderr)


if __name__ == "__main__":
    main()
