#!/usr/bin/env bash
# =============================================================
# Create Cedar Policies via AgentCore API
#
# This script creates the Policy Engine and Cedar policies that
# the Terraform AWS provider doesn't support yet. It writes the
# resulting ARNs to terraform/policy-arns.auto.tfvars so Terraform
# can reference them.
#
# Usage:
#   ./scripts/create-policies.sh [gateway-arn]
#
# If gateway-arn is not provided, it reads from terraform output.
#
# Prerequisites:
#   - aws CLI configured
#   - jq installed
#   - Terraform applied (gateway must exist for tool-specific policies)
# =============================================================

set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
TERRAFORM_DIR="$(dirname "$0")/../terraform"
POLICY_ENGINE_NAME="DataPlatformAuth"
VARS_FILE="${TERRAFORM_DIR}/policy-arns.auto.tfvars"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${YELLOW}→${NC} $1"; }
done() { echo -e "${GREEN}✓${NC} $1"; }

# --- Get or create Policy Engine ---

info "Checking for existing policy engine..."
ENGINE_ID=$(aws bedrock-agentcore-control list-policy-engines \
  --region "$REGION" \
  --query "policyEngines[?starts_with(name, '${POLICY_ENGINE_NAME}')].policyEngineId | [0]" \
  --output text 2>/dev/null || echo "None")

if [[ "$ENGINE_ID" == "None" || -z "$ENGINE_ID" ]]; then
  info "Creating policy engine: ${POLICY_ENGINE_NAME}..."
  ENGINE_RESULT=$(aws bedrock-agentcore-control create-policy-engine \
    --region "$REGION" \
    --name "$POLICY_ENGINE_NAME" \
    --description "Cedar authorization for the data platform gateway" \
    --output json)
  ENGINE_ID=$(echo "$ENGINE_RESULT" | jq -r '.policyEngineId')
  ENGINE_ARN=$(echo "$ENGINE_RESULT" | jq -r '.policyEngineArn')

  info "Waiting for policy engine to become ACTIVE..."
  while true; do
    STATUS=$(aws bedrock-agentcore-control get-policy-engine \
      --region "$REGION" \
      --policy-engine-id "$ENGINE_ID" \
      --query "status" --output text)
    [[ "$STATUS" == "ACTIVE" ]] && break
    sleep 5
  done
  done "Policy engine ACTIVE: $ENGINE_ID"
else
  ENGINE_ARN=$(aws bedrock-agentcore-control get-policy-engine \
    --region "$REGION" \
    --policy-engine-id "$ENGINE_ID" \
    --query "policyEngineArn" --output text)
  done "Policy engine already exists: $ENGINE_ID"
fi

# --- Get Gateway ARN ---

GATEWAY_ARN="${1:-}"
if [[ -z "$GATEWAY_ARN" ]]; then
  info "Reading gateway ARN from terraform output..."
  GATEWAY_ARN=$(terraform -chdir="$TERRAFORM_DIR" output -raw gateway_arn 2>/dev/null || echo "")
fi

if [[ -z "$GATEWAY_ARN" ]]; then
  echo "ERROR: Gateway ARN not available. Deploy the gateway with Terraform first." >&2
  echo "       Run: cd terraform && terraform apply" >&2
  echo "       Then re-run this script." >&2
  echo "" >&2
  echo "Writing partial vars file with policy engine ARN only..." >&2
  cat > "$VARS_FILE" <<EOF
# Auto-generated by scripts/create-policies.sh
# Re-run after gateway is deployed to add tool-specific policies.
policy_engine_arn = "${ENGINE_ARN}"
policy_engine_id  = "${ENGINE_ID}"
EOF
  done "Wrote ${VARS_FILE} (partial — no tool-specific policies yet)"
  exit 0
fi

done "Gateway ARN: $GATEWAY_ARN"

# --- Helper: create policy if it doesn't exist ---

create_policy() {
  local name="$1"
  local description="$2"
  local statement="$3"

  # Check if policy already exists
  EXISTING=$(aws bedrock-agentcore-control list-policies \
    --region "$REGION" \
    --policy-engine-id "$ENGINE_ID" \
    --query "policies[?name=='${name}'].policyId | [0]" \
    --output text 2>/dev/null || echo "None")

  if [[ "$EXISTING" != "None" && -n "$EXISTING" ]]; then
    done "Policy already exists: $name ($EXISTING)"
    return
  fi

  info "Creating policy: $name..."
  aws bedrock-agentcore-control create-policy \
    --region "$REGION" \
    --policy-engine-id "$ENGINE_ID" \
    --name "$name" \
    --description "$description" \
    --definition "{\"cedar\":{\"statement\":\"$statement\"}}" \
    --validation-mode IGNORE_ALL_FINDINGS \
    --output text --query "policyId" > /dev/null

  done "Created: $name"
}

# --- Create Policies ---

info "Creating Cedar policies..."

# Admin: full access (wildcard resource)
create_policy "AdminFullAccess" \
  "Admins can invoke all database tools without restriction" \
  "permit(principal in AgentCore::Group::\"admins\", action, resource is AgentCore::Gateway);"

# Engineering: specific tool access
create_policy "EngineeringRunQuery" \
  "Engineers can run queries" \
  "permit(principal in AgentCore::Group::\"engineering\", action == AgentCore::Action::\"DatabaseTools___run_query\", resource == AgentCore::Gateway::\"${GATEWAY_ARN}\");"

create_policy "EngineeringListTables" \
  "Engineers can list tables" \
  "permit(principal in AgentCore::Group::\"engineering\", action == AgentCore::Action::\"DatabaseTools___list_tables\", resource == AgentCore::Gateway::\"${GATEWAY_ARN}\");"

create_policy "EngineeringDescribeTable" \
  "Engineers can describe tables" \
  "permit(principal in AgentCore::Group::\"engineering\", action == AgentCore::Action::\"DatabaseTools___describe_table\", resource == AgentCore::Gateway::\"${GATEWAY_ARN}\");"

create_policy "EngineeringForbidDelete" \
  "Engineers cannot delete records" \
  "forbid(principal in AgentCore::Group::\"engineering\", action == AgentCore::Action::\"DatabaseTools___delete_records\", resource == AgentCore::Gateway::\"${GATEWAY_ARN}\");"

# Marketing: limited access
create_policy "MarketingListTables" \
  "Marketing can list tables" \
  "permit(principal in AgentCore::Group::\"marketing\", action == AgentCore::Action::\"DatabaseTools___list_tables\", resource == AgentCore::Gateway::\"${GATEWAY_ARN}\");"

create_policy "MarketingDescribeTable" \
  "Marketing can describe tables" \
  "permit(principal in AgentCore::Group::\"marketing\", action == AgentCore::Action::\"DatabaseTools___describe_table\", resource == AgentCore::Gateway::\"${GATEWAY_ARN}\");"

# --- Write Terraform vars file ---

info "Writing policy ARNs to ${VARS_FILE}..."

cat > "$VARS_FILE" <<EOF
# Auto-generated by scripts/create-policies.sh
# Do not edit manually — re-run the script to update.
policy_engine_arn = "${ENGINE_ARN}"
policy_engine_id  = "${ENGINE_ID}"
EOF

done "All policies created and ${VARS_FILE} written."
echo ""
echo "Next: run 'terraform apply' to attach the policy engine to the gateway."
